id: A53B432C6
title: f0387
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 16:32:38.497326
  last_modified_at: 2022-05-27 16:32:38.497334
