id: A53B432C6
title: fA67A
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 16:32:38.576545
  last_modified_at: 2022-05-27 16:32:38.576548
